default:
	just -l

dev: db-clean db-gen db-migrate db-seed grafbase-dev

db-clean:
	rm drizzle/local.db || true

db-gen:
	cd drizzle && bunx drizzle-kit generate:sqlite

db-migrate:
	cd drizzle && bun migrate.ts

db-seed:
	cd drizzle && bun seed.ts

db-studio:
	cd drizzle && bunx drizzle-kit studio

grafbase-dev:
	grafbase dev

migrate:
	cd drizzle && op run -- bun run migrate.ts

publish:
	rm -rf .devenv .direnv
	grafbase deploy
	sleep 180
	grafbase introspect https://show-hosts-rawkodeacademy.grafbase.app/graphql | grafbase publish --name show-hosts --url https://show-hosts-rawkodeacademy.grafbase.app/graphql rawkodeacademy/api
