import { spawn } from "node:child_process";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

type Subgraph = {
	name: string;
	routingUrl: string;
	publisherEntrypoint: string;
	schemaFile: string;
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const platformRoot = path.resolve(projectRoot, "..");
const generatedDir = path.join(projectRoot, "src", "generated");
const artifactsDir = path.join(projectRoot, ".supergraph");
const supergraphConfigPath = path.join(artifactsDir, "supergraph.yaml");
const supergraphGraphqlPath = path.join(artifactsDir, "supergraph.graphql");
const supergraphTargetPath = path.join(generatedDir, "supergraph.ts");

const subgraphs: Subgraph[] = [
	{
		name: "emojiReactions",
		routingUrl: "https://platform-emoji-reactions-read-model.rawkode-academy.workers.dev/graphql",
		publisherEntrypoint: path.join(platformRoot, "emoji-reactions", "read-model", "publish.ts"),
		schemaFile: path.join(platformRoot, "emoji-reactions", "read-model", "schema.gql"),
	},
	{
		name: "emailPreferences",
		routingUrl: "https://platform-email-preferences-read-model.rawkode-academy.workers.dev/graphql",
		publisherEntrypoint: path.join(platformRoot, "email-preferences", "read-model", "publish.ts"),
		schemaFile: path.join(platformRoot, "email-preferences", "read-model", "schema.gql"),
	},
	{
		name: "people",
		routingUrl: "https://platform-people-read-model.rawkode-academy.workers.dev/graphql",
		publisherEntrypoint: path.join(platformRoot, "people", "read-model", "publish.ts"),
		schemaFile: path.join(platformRoot, "people", "read-model", "schema.gql"),
	},
];

const roverExecutable = path.join(
	projectRoot,
	"node_modules",
	".bin",
	process.platform === "win32" ? "rover.cmd" : "rover",
);

function toPosixRelative(target: string) {
	return path.relative(projectRoot, target).split(path.sep).join(path.posix.sep);
}

async function runPublisher(subgraph: Subgraph) {
	const moduleUrl = pathToFileURL(subgraph.publisherEntrypoint).href;
	console.info(`📝 Publishing schema for ${subgraph.name}`);
	await import(moduleUrl);
	await access(subgraph.schemaFile);
}

function generateSupergraphConfig() {
	const lines: string[] = ["federation_version: =2.9.0", "subgraphs:"];
	for (const subgraph of subgraphs) {
		lines.push(`  ${subgraph.name}:`);
		lines.push(`    routing_url: ${subgraph.routingUrl}`);
		lines.push("    schema:");
		lines.push(`      file: ${toPosixRelative(subgraph.schemaFile)}`);
	}
	return lines.join("\n");
}

async function runRover() {
	console.info("🕸️ Composing federated supergraph with Rover");
	await new Promise<void>((resolve, reject) => {
		const child = spawn(
			roverExecutable,
			[
				"supergraph",
				"compose",
				"--elv2-license=accept",
				"--config",
				supergraphConfigPath,
				"--output",
				supergraphGraphqlPath,
			],
			{
				stdio: "inherit",
			},
		);
		child.on("exit", (code) => {
			if (code === 0) {
				resolve();
			} else {
				reject(new Error(`Rover exited with code ${code ?? -1}`));
			}
		});
		child.on("error", (err) => reject(err));
	});
}

function escapeForTemplateLiteral(sdl: string) {
	return sdl.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function writeGeneratedModule() {
	const sdl = await readFile(supergraphGraphqlPath, "utf8");
	const contents = `// This file is auto-generated by \`bun run supergraph:build\`\nexport const supergraphSdl = \`\n${escapeForTemplateLiteral(
		sdl,
	)}\`;\n`;
	await writeFile(supergraphTargetPath, contents);
	console.info(`✅ Updated ${toPosixRelative(supergraphTargetPath)}`);
}

await mkdir(artifactsDir, { recursive: true });
await mkdir(generatedDir, { recursive: true });
await access(roverExecutable).catch(() => {
	throw new Error(
		`Rover CLI is not installed. Run \`npm install\` before composing the supergraph.`,
	);
});

for (const subgraph of subgraphs) {
	await runPublisher(subgraph);
}

const configContents = generateSupergraphConfig();
await writeFile(supergraphConfigPath, configContents);

await runRover();
await writeGeneratedModule();
