apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ngrok
spec:
  interval: 48h
  url: https://charts.ngrok.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngrok
spec:
  interval: 72h
  timeout: 5m
  chart:
    spec:
      chart: ngrok-operator
      version: '0.13.*'
      sourceRef:
        kind: HelmRepository
        name: ngrok
      interval: 5m
  releaseName: ngrok-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    replicaCount: 1
    useExperimentalGatewayApi: true
    credentials:
      secret:
        # API_KEY and AUTHTOKEN must exist
        name: ngrok-operator-credentials
    # TODO: Not supported by chart
    # nodeSelector:
    #   cloud.google.com/gke-spot: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
