default:
	just -l

dev: db-clean db-gen db-migrate db-seed grafbase-dev

db-clean:
	rm drizzle/local.db || true

db-gen:
	cd drizzle && bun x drizzle-kit generate

db-migrate:
	cd drizzle && bun migrate.ts

db-seed:
	cd drizzle && bun seed.ts

db-studio:
	cd drizzle && bun x drizzle-kit studio

grafbase-dev:
	grafbase dev --port 4020

migrate:
	cd drizzle && op run -- bun run migrate.ts

publish:
	grafbase deploy
	grafbase introspect https://querytube-rawkodeacademy.grafbase.app/graphql | grafbase publish --name querytube --url https://querytube-rawkodeacademy.grafbase.app/graphql rawkodeacademy/api
