# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json
version: "1"
log_level: debug
authentication:
  providers:
    - name: WorkOS
      jwks:
        url: "https://zitadel.rawkode.academy/oauth/v2/keys"

headers:
  all:
    request:
      - op: propagate
        named: Authorization
