app = 'rawkode-academy-api'
primary_region = 'lhr'

[build]
image = "ghcr.io/ardatan/hive-gateway"

[experimental]
cmd = ["supergraph"]

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2

[deploy]
strategy = "immediate"
