[graph]
path = "/"
introspection = true

[gateway]
timeout = "30s"
subgraph_timeout = "4s"

[gateway.rate_limit.global]
limit = 100
duration = "10s"

[gateway.retry]
enabled = true
min_per_second = 10
ttl = "1s"
retry_percent = 0.1
retry_mutations = false

[network]
listen_address = "0.0.0.0:5000"

# [operation_limits]
# depth = 10
# height = 12
# aliases = 5
# root_fields = 6
# complexity = 8
