app = 'rawkode-academy-zitadel'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "5s"
  path = "/debug/ready"

[[vm]]
  size = 'shared-cpu-2x'
  cpu_kind = 'shared'
  cpus = 2
  memory = '2gb'
