app = 'rawkode-academy-zitadel'
primary_region = 'lhr'

[build]
dockerfile = 'Dockerfile'

[deploy]
strategy = 'immediate'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1

[[vm]]
size = 'shared-cpu-4x'
memory = "4GB"
