.docker:
  image: docker:latest
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: "27.2.0"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
  before_script:
    - until docker info > /dev/null 2>&1; do sleep 1; done

.dagger:
  extends: [.docker]
  before_script:
    - apk add ca-certificates curl git
    - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh

stages:
  - deploy

website-deploy-production:
  extends: [.dagger]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - projects/rawkode.academy/website/**/*
  script:
    - cd projects/rawkode.academy/website
    - |
      dagger <<.
        . | build | export dist

        ../../../dagger/cloudflare | deploy \
          ./dist \
          wrangler.toml \
          env:CLOUDFLARE_PAGES_TOKEN \
          env:CICD_COMMENT_TOKEN
      .

website-deploy-merge-request:
  extends: [.dagger]
  stage: deploy
  rules:
    - if: "$CI_MERGE_REQUEST_ID"
      changes:
        - projects/rawkode.academy/website/**/*
  script:
    - cd projects/rawkode.academy/website
    - |
      dagger <<.
        . | build | export dist

        ../../../dagger/cloudflare | deploy \
          ./dist \
          wrangler.toml \
          env:CLOUDFLARE_PAGES_TOKEN \
          env:CICD_COMMENT_TOKEN \
          --merge-request-id=$CI_MERGE_REQUEST_ID
      .

studio-deploy-production:
  extends: [.dagger]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - projects/rawkode.studio/**/*
  script:
    - cd projects/rawkode.studio
    - |
      dagger <<.
        . | build | export dist

        ../../dagger/cloudflare | deploy \
          ./dist \
          wrangler.toml \
          env:CLOUDFLARE_PAGES_TOKEN \
          env:CICD_COMMENT_TOKEN
      .

studio-deploy-merge-request:
  extends: [.dagger]
  stage: deploy
  rules:
    - if: "$CI_MERGE_REQUEST_ID"
      changes:
        - projects/rawkode.studio/**/*
  script:
    - cd projects/rawkode.studio
    - |
      dagger <<.
        . | build | export dist

        ../../dagger/cloudflare | deploy \
          ./dist \
          wrangler.toml \
          env:CLOUDFLARE_PAGES_TOKEN \
          env:CICD_COMMENT_TOKEN \
          --merge-request-id=$CI_MERGE_REQUEST_ID
      .
