packages:
  - "./dagger"
  - "./projects/core-infrastructure/gcp-control-plane"
  - "./projects/core-infrastructure/dns"
  - "./projects/rawkode.academy/website"
  - "./projects/rawkode.cloud/google-cloud"
  - "./projects/rawkode.cloud/teleport"
  - "./projects/rawkode.studio"
  - "./projects/rawkode.studio/deploy"
  - "./projects/rawkode.studio/workflows-youtube"
