packages:
  - "./dagger"
  - "./projects/core-infrastructure/gcp-control-plane"
  - "./projects/core-infrastructure/terraform-bootstrap"
  - "./projects/core-infrastructure/dns"
  - "./projects/core-infrastructure/kubernetes-platform"
  - "./projects/rawkode.academy/website"
  - "./projects/rawkode.cloud/infrastructure"
  - "./projects/rawkode.community/ics-events"
  - "./projects/rawkode.studio"
  - "./projects/rawkode.studio/content-management/desktop"
  - "./projects/rawkode.studio/deploy"
  - "./projects/rawkode.studio/workflows-youtube"
