default:
	just -l

db-clean:
	rm drizzle/local.db

db-gen:
	cd drizzle && bunx drizzle-kit generate:sqlite

db-migrate:
	cd drizzle && bun migrate.ts

db-seed:
	cd drizzle && bun seed.ts

db-studio:
	cd drizzle && bunx drizzle-kit studio

deploy:
	cd drizzle && infisical run --path /projects/rawkode-academy/rsvp-service --env production -- bun migrate.ts
	grafbase deploy

publish:
	grafbase introspect https://rsvp-rawkodeacademy.grafbase.app/graphql | grafbase publish --name rsvp --url https://rsvp-rawkodeacademy.grafbase.app/graphql rawkodeacademy/api
