name = "rawkode-single-user-pds"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[vars]
PDS_DID = "did:web:rawkode.social"
PDS_HANDLE = "rawkode.social"

[[d1_databases]]
binding = "DB"
database_name = "rawkode_pds"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "BLOBS"
bucket_name = "rawkode-pds-posts"

[[kv_namespaces]]
binding = "SETTINGS"
id = "00000000000000000000000000000000"

[[durable_objects.bindings]]
name = "FIREHOSE_DO"
class_name = "FirehoseDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["FirehoseDurableObject"]
