# Example project-specific dbt configuration
name: 'my_project_analytics'
version: '1.0.0'
config-version: 2

profile: 'my_project_analytics'

model-paths: ["models"]
test-paths: ["tests"]

# Import the base analytics macros
# In a real project, this would reference the published package
macro-paths: ["../../dbt/macros"]

models:
  my_project_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: my_project_analytics