deploy-read-model:
	#!/usr/bin/env bash
	bunx wrangler -c ./read-model/wrangler.jsonc deploy --var SERVICE_NAME:${SERVICE_NAME} --var LIBSQL_BASE_URL:${LIBSQL_BASE_URL}

	bun run read-model/publish.ts
	bunx wgc subgraph publish ${SERVICE_NAME} --namespace production --schema ./read-model/schema.gql
	bunx wgc subgraph update ${SERVICE_NAME} --namespace production --routing-url https://${SERVICE_NAME}-read-model.rawkodeacademy.workers.dev

deploy-write-model:
	#!/usr/bin/env bash
	bun build --target bun --outdir write-model/dist write-model/main.ts
	bunx wrangler -c ./write-model/wrangler.jsonc deploy --var SERVICE_NAME:${SERVICE_NAME} --var LIBSQL_BASE_URL:${LIBSQL_BASE_URL}
