apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
spec:
  interval: 72h
  timeout: 5m
  chart:
    spec:
      chart: memcached
      version: '7.5.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: memcached
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    architecture: standalone
    auth:
      enabled: true
      username: "zulip@localhost"
    containerSecurityContext:
      # Can't enable authentication if
      # we can't write the config to the
      # root file system
      readOnlyRootFilesystem: false
