apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  interval: 72h
  timeout: 5m
  chart:
    spec:
      chart: rabbitmq
      version: '15.1.*'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: rabbitmq
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    architecture: standalone
    auth:
      username: "zulip"
