default:
	just -l

dev: db-clean db-gen db-migrate db-seed grafbase-dev

db-clean:
	rm drizzle/local.db || true

db-gen:
	cd drizzle && bunx drizzle-kit generate:sqlite

db-migrate:
	cd drizzle && bun migrate.ts

db-seed:
	cd drizzle && bun seed.ts

db-studio:
	cd drizzle && bunx drizzle-kit studio

grafbase-dev:
	grafbase dev --port 4020

deploy:
	cd drizzle && infisical run --path /projects/rawkode-academy/content-system/shows-service --env production -- bun migrate.ts
	grafbase deploy

publish:
	grafbase introspect https://shows-rawkodeacademy.grafbase.app/graphql | grafbase publish --name shows --url https://shows-rawkodeacademy.grafbase.app/graphql rawkodeacademy/api
