DROP VIEW IF EXISTS "show_hosts_view";
DROP VIEW IF EXISTS "host_shows_view";
DROP VIEW IF EXISTS "episode_guests_view";
DROP VIEW IF EXISTS "guest_episodes_view";
DROP TABLE IF EXISTS "show_hosts";
DROP TABLE IF EXISTS "shows";
DROP TABLE IF EXISTS "people";
DROP TABLE IF EXISTS "technologies";
DROP TABLE IF EXISTS "episode_guests";
DROP TABLE IF EXISTS "episodes";
DROP TYPE "chapter";
