name = "casting-credits-read-model"
main = "./main.ts"

workers_dev = true
logpush = false

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

secrets_store_secrets = [
  { binding = "LIBSQL_TOKEN", store_id= "492e5e40b9d64ebeac7e7a77db91ff6e", secret_name = "LIBSQL_TOKEN_PLATFORM" }
]


tail_consumers = [{service = "casting-credits-read-model-tail-sentry"}, {service = "casting-credits-read-model-tail-baselime"}]

[observability.logs]
enabled = true
