version = 1

[install]
bun.pkg-path = "bun"
nodejs.pkg-path = "nodejs"
rover.pkg-path = "rover"
sqld.pkg-path = "sqld"
turso-cli.pkg-path = "turso-cli"
flyctl.pkg-path = "flyctl"
cargo.pkg-path = "cargo"
wasmer.flake = "github:NixOS/nixpkgs/nixpkgs-unstable#wasmer"
deno.flake = "github:NixOS/nixpkgs/nixpkgs-unstable#deno"
scaleway-cli.pkg-path = "scaleway-cli"
google-cloud-sdk.pkg-path = "google-cloud-sdk"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
