version = 1

[install]
bun.pkg-path = "bun"
deno.pkg-path = "deno"
nodejs.pkg-path = "nodejs"
rover.pkg-path = "rover"
sqld.pkg-path = "sqld"
turso-cli.pkg-path = "turso-cli"
flyctl.pkg-path = "flyctl"
cargo.pkg-path = "cargo"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
