name: rawkode.academy/website/deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rawkode-academy-website.yaml"
      - "projects/rawkode.academy/website/**"
  schedule:
    - cron: "12 4 * * *"

permissions:
   pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest
      - shell: bash
        working-directory: "projects/rawkode.academy/website"
        run: source .env
      - name: deploy
        # https://github.com/cloudflare/wrangler-action/issues/347
        # https://github.com/cloudflare/wrangler-action/issues/329
        uses: cloudflare/wrangler-action@v3.12.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: bun
          command: pages deploy --project-name=rawkode-academy ./dist
          workingDirectory: "projects/rawkode.academy/website"
          preCommands: |
            devenv shell bun run build
