name: rawkode.academy/website/preview

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/rawkode-academy-website-preview.yaml"
      - "projects/rawkode.academy/website/**"

permissions:
   pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    name: preview
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - shell: bash
        working-directory: "projects/rawkode.academy/website"
        run: source .env
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest
      - id: preview
        name: preview
        # https://github.com/cloudflare/wrangler-action/issues/347
        # https://github.com/cloudflare/wrangler-action/issues/329
        uses: cloudflare/wrangler-action@v3.12.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: bun
          command: pages deploy --project-name=rawkode-academy ./dist
          workingDirectory: "projects/rawkode.academy/website"
          preCommands: |
            devenv shell bun run build
      - name: comment-with-preview-url
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          message: |
            🌐 Your preview deployment can be viewed now 🚀

            ${{ steps.preview.outputs.deployment-url }}
