name: ⚡ Action
description: Define a specific action item for immediate execution
title: "[ACTION] "
labels: ["action"]
body:
  - type: markdown
    attributes:
      value: |
        **Note for maintainers:** This issue should be added to the **Product Planning** project for triage.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product does this action relate to?
      options:
        - rawkode.academy
        - rawkode.studio
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Action Description
      description: Clearly describe the specific action that needs to be taken
      placeholder: What specific action needs to be performed?
    validations:
      required: true

  - type: dropdown
    id: action_type
    attributes:
      label: Action Type
      description: What category does this action fall into?
      options:
        - Decision Required
        - Approval Needed
        - Communication
        - Documentation
        - Configuration Change
        - Process Update
        - Investigation
        - Coordination
        - Follow-up
        - Other
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this action needed? What's driving this requirement?
      placeholder: Explain the reasoning or context behind this action
    validations:
      required: true

  - type: textarea
    id: owner
    attributes:
      label: Suggested Owner/Assignee
      description: Who should be responsible for this action?
      placeholder: |
        - Primary owner: @username
        - Supporting team/people: @team or @username
        - Decision makers: @username

  - type: textarea
    id: deadline
    attributes:
      label: Deadline/Timeline
      description: When does this action need to be completed?
      placeholder: |
        - Deadline: [specific date]
        - Urgency: [why this timing is important]
        - Dependencies: [what depends on this action]

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How will we know this action has been completed successfully?
      placeholder: |
        - [ ] Specific outcome 1
        - [ ] Specific outcome 2
        - [ ] Deliverable or artifact produced
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact & Consequences
      description: What happens if this action is completed? What if it's not?
      placeholder: |
        - If completed: [positive outcomes]
        - If not completed: [risks or negative consequences]
        - Who/what is affected: [stakeholders, systems, processes]

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or background
      placeholder: Include any relevant links, previous discussions, or related issues

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this action?
      options:
        - Low - Can wait for next planning cycle
        - Medium - Should be addressed within 2 weeks
        - High - Needs attention within a few days
        - Critical - Immediate action required
    validations:
      required: true