name: 🎯 Activity
description: Plan an activity for product development or community engagement
title: "[ACTIVITY] "
labels: ["activity"]
projects: ["RawkodeAcademy/3"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product does this activity relate to?
      options:
        - rawkode.academy
        - rawkode.studio
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Activity Description
      description: Describe the activity you want to plan
      placeholder: What activity are you proposing and what would it involve?
    validations:
      required: true

  - type: dropdown
    id: activity_type
    attributes:
      label: Activity Type
      description: What type of activity is this?
      options:
        - Research & Analysis
        - User Research
        - Market Analysis
        - Competitive Analysis
        - Content Planning
        - Community Engagement
        - Partnership Development
        - Strategic Planning
        - Process Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: objectives
    attributes:
      label: Objectives & Goals
      description: What are the main objectives and expected outcomes?
      placeholder: |
        - Objective 1: [specific goal]
        - Objective 2: [specific goal]
        - Success metric: [how will you measure success]
    validations:
      required: true

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience
      description: Who is the target audience or stakeholder group?
      placeholder: Who will benefit from or participate in this activity?

  - type: textarea
    id: timeline
    attributes:
      label: Proposed Timeline
      description: What's the proposed timeline for this activity?
      placeholder: |
        - Start date: [when should this begin]
        - Duration: [how long will it take]
        - Key milestones: [important dates or checkpoints]

  - type: textarea
    id: resources_needed
    attributes:
      label: Resources Needed
      description: What resources, tools, or support will be required?
      placeholder: |
        - People: [who needs to be involved]
        - Tools: [what tools or platforms are needed]
        - Budget: [any financial considerations]
        - External resources: [third-party services, etc.]

  - type: textarea
    id: deliverables
    attributes:
      label: Expected Deliverables
      description: What outputs or deliverables will this activity produce?
      placeholder: |
        - Deliverable 1: [what will be created]
        - Deliverable 2: [what will be created]
        - Format: [how will results be documented/shared]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What's the priority level for this activity?
      options:
        - Low - Future consideration
        - Medium - Next quarter planning
        - High - Current quarter priority
        - Urgent - Immediate planning needed
    validations:
      required: true