name: 🎯 Activity
description: Define a user goal or outcome they want to achieve (user story mapping)
title: "[ACTIVITY] "
labels: ["activity"]
body:
  - type: markdown
    attributes:
      value: |
        **User Story Mapping:** Activities represent the goals users want to achieve. Actions describe how they achieve those goals.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product does this user goal relate to?
      options:
        - rawkode.academy
        - rawkode.studio
    validations:
      required: true

  - type: textarea
    id: user_goal
    attributes:
      label: User Goal
      description: What goal does the user want to achieve?
      placeholder: "As a [user type], I want to [achieve goal] so that [benefit/value]"
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: What type of user is trying to achieve this goal?
      options:
        - Content Creator
        - Course Student/Learner
        - Community Member
        - Educator/Instructor
        - Developer/Technical User
        - Content Consumer
        - Platform Administrator
        - Partner/Collaborator
        - New User/Visitor
        - Other
    validations:
      required: true

  - type: textarea
    id: user_context
    attributes:
      label: User Context
      description: In what situation or context would a user have this goal?
      placeholder: |
        - When does this need arise for the user?
        - What triggers this goal?
        - What's the user's current state/situation?
    validations:
      required: true

  - type: textarea
    id: success_outcome
    attributes:
      label: Success Outcome
      description: What does success look like for the user when they achieve this goal?
      placeholder: |
        - How will the user know they've succeeded?
        - What value do they gain?
        - What can they do next?
    validations:
      required: true

  - type: dropdown
    id: user_journey_stage
    attributes:
      label: User Journey Stage
      description: At what stage of their journey would users have this goal?
      options:
        - Discovery - Finding the platform
        - Onboarding - Getting started
        - Learning - Consuming content
        - Creating - Producing content
        - Engaging - Community participation
        - Advanced - Deep platform usage
        - Advocacy - Sharing/recommending
    validations:
      required: true

  - type: textarea
    id: pain_points
    attributes:
      label: Current Pain Points
      description: What challenges or frustrations do users face when trying to achieve this goal?
      placeholder: |
        - What barriers exist today?
        - What makes this difficult for users?
        - What workarounds do they currently use?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this user goal to the overall user experience?
      options:
        - Low - Nice to have, enhances experience
        - Medium - Important for user satisfaction
        - High - Critical for core user experience
        - Essential - Must-have for platform success
    validations:
      required: true