blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/RawkodeAcademy/RawkodeAcademy/discussions
    about: For questions, ideas, or general discussion about Rawkode Academy
  - name: 💡 Discord Community
    url: https://rawkode.chat
    about: Join our Discord community for real-time discussions and support