name: ✨ Feature Request
description: Suggest a new feature or enhancement for Rawkode Academy
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        **Note for maintainers:** This issue should be added to the **Ship Happens** project for tracking and triage.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product does this feature request affect?
      options:
        - rawkode.academy
        - rawkode.studio
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a clear and concise description of the feature you'd like to see
      placeholder: As a [user type], I want [feature] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the current limitation or problem that this feature would address
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution and how it should work
      placeholder: Detail how you envision this feature working
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've considered

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that help explain the feature request
      placeholder: Any additional information that would be helpful

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How would you rate the priority of this feature?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for workflows
        - Critical - Blocking current work
    validations:
      required: true