name: 🐛 New Defect
description: Is something broken? 😱
type: Defect
assignees:
  - rawkode
  - icepuma
body:
  - type: markdown
    attributes:
      value: |
        **Want to discuss this issue first?**

        Join the [Discord](https://rawkode.chat) and let's chat!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
      value: |
        # Defect

        What did you notice was not working correctly?

    validations:
      required: true

  - type: dropdown
    id: assignee
    attributes:
      label: Do you want us to assign this issue to you?
      multiple: false
      default: 0
      options:
        - "No"
        - "Yes"
    validations:
      required: false
