name: 🔁 New Change
description: Use this template to suggest a new change
labels:
  - type/change
assignees:
  - rawkode
  - icepuma
body:
  - type: checkboxes
    id: existing-issues-check
    attributes:
      label: Check for existing issues
      description: Please check the list of existing issues for duplicates; if a change request already exists, give it a `+1` (👍).
      options:
        - label: Completed
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your proposed change in your own words
    validations:
      required: true

  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to help us with implementing the change? (If "Yes", we assign you the ticket)
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        You can also join our Discord [here](http://rawkode.chat).
