name: 📋 Task
description: Request a specific task or work item for Rawkode Academy
title: "[TASK] "
labels: ["task"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product does this task relate to?
      options:
        - rawkode.academy
        - rawkode.studio
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Provide a clear description of the task that needs to be completed
      placeholder: Describe what needs to be done and why
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the criteria that must be met for this task to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Background
      description: Provide any relevant context or background information for this task
      placeholder: Why is this task needed? What's the background or motivation?

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies or prerequisites for this task
      placeholder: |
        - Depends on: #issue_number
        - Requires: specific resource or access
        - Blocked by: external factor

  - type: textarea
    id: resources
    attributes:
      label: Resources & References
      description: Include any helpful resources, links, or documentation
      placeholder: |
        - Documentation: [link]
        - Related issues: #123, #456
        - Reference materials: [links]

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: What's your estimate of the effort required?
      options:
        - XS - Less than 1 hour
        - S - 1-4 hours
        - M - 1-2 days
        - L - 3-5 days
        - XL - More than 1 week

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What's the priority level for this task?
      options:
        - Low - Can be done when time permits
        - Medium - Should be completed in current cycle
        - High - Important for current goals
        - Urgent - Needs immediate attention
    validations:
      required: true