apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ngrok
  namespace: flux-system
spec:
  provider: gcp
  interval: 5m0s
  url: oci://europe-west2-docker.pkg.dev/rawkode-academy-production/rawkode-academy/ngrok
  ref:
    semver: 'v1.0.*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: ngrok
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngrok
  namespace: flux-system
spec:
  targetNamespace: ngrok
  interval: 15m0s
  path: ./
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: OCIRepository
    name: ngrok
  timeout: 3m0s
  wait: true
