[project]
name = "video-categorizer"
version = "0.1.0"
description = "Categorize videos and generate SQL for episodes table"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "boto3>=1.28.0",
]

[tool.uv]
dev-dependencies = []