schema @link(url: "https://specs.apollo.dev/federation/v2.6", import: ["@key"]) {
  query: Query
}

type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
  allShows: [Show!]
  showById(id: String!): Show
}

type Show @key(fields: "id") {
  id: String
  name: String
}

scalar _Any

union _Entity = Show

type _Service {
  """
  The sdl representing the federated service capabilities. Includes federation directives, removes federation types, and includes rest of full schema after schema directives have been applied
  """
  sdl: String
}