@default:
	just --list

dev:
	bun run astro dev

format:
	nixfmt .
	biome format --write src/

build:
	bun run astro check
	bun run astro build

test:
	bun run vitest

test-with-logs:
	bun run vitest --reporter=basic --no-file-parallelism --disable-console-intercept

deploy:
	op run -- bun run wrangler pages deploy --branch main dist

preview:
	bun run astro preview

codegen:
	bun run graphql-codegen --config graphql-codegen.ts
