// Generated by Wrangler on Wed Jul 24 2024 11:09:53 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	REDIRECT_URL: string;
	WORKOS_CLIENT_ID: string;
	WORKOS_API_KEY: string;
	WORKOS_COOKIE_PASSWORD: string;
}
