// Generated by Wrangler on Tue Jul 23 2024 09:29:25 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	REDIRECT_URL: string;
	WORKOS_CLIENT_ID: string;
	WORKOS_API_KEY: string;
	WORKOS_COOKIE_PASSWORD: string;
}
