//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "show")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::person::Entity> for Entity {
    fn to() -> RelationDef {
        super::show_hosts::Relation::Person.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::show_hosts::Relation::Show.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
