name = "social-random-video"
main = "src/index.ts"

compatibility_date = "2025-05-05"

[ai]
binding = "AI"

[[workflows]]
binding = "SOCIAL_VIDEO_WORKFLOW"
name = "social-video-workflow"
class_name = "SocialVideoWorkflow"
