/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    people: Person;
    categories: Category;
    posts: Post;
    shows: Show;
    episodes: Episode;
    technologies: Technology;
    logo: Logo;
    search: Search;
  };
  globals: {};
}
export interface Person {
  id: string;
  name: string;
  github: string;
  role: 'admin' | 'editor' | 'guest';
  socialMedia?: {
    twitter?: string;
    linkedin?: string;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Category {
  id: string;
  name?: string;
}
export interface Post {
  id: string;
  title?: string;
  author?: string | Person;
  publishedDate?: string;
  category?: string | Category;
  content?: {
    [k: string]: unknown;
  }[];
  status?: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
export interface Show {
  id: string;
  name?: string;
  hosts?: string[] | Person[];
  slug?: string;
}
export interface Episode {
  id: string;
  name?: string;
  show?: string | Show;
  guests?: string[] | Person[];
}
export interface Technology {
  id: string;
  name?: string;
  logo?: string | Logo;
  description: {
    [k: string]: unknown;
  }[];
  hashtag?: string;
  homepage: string;
  documentation: string;
  socialMedia?: {
    twitter?: string;
    linkedin?: string;
  };
  openSource?: boolean;
  openSourceDetails?: {
    repository: string;
  };
  slug?: string;
}
export interface Logo {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    sq960?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    sq1440?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    sq1920?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Search {
  id: string;
  title?: string;
  priority?: number;
  doc:
    | {
        value: string | Person;
        relationTo: 'people';
      }
    | {
        value: string | Category;
        relationTo: 'categories';
      }
    | {
        value: string | Post;
        relationTo: 'posts';
      }
    | {
        value: string | Show;
        relationTo: 'shows';
      }
    | {
        value: string | Episode;
        relationTo: 'episodes';
      }
    | {
        value: string | Technology;
        relationTo: 'technologies';
      }
    | {
        value: string | Logo;
        relationTo: 'logo';
      };
  updatedAt: string;
  createdAt: string;
}
