direction: down

learner: {
  shape: person
}

website: {
	shape: document
  tooltip: |md
    The website is built with Astro and hosted on Cloudflare Pages. Primarily static, it does use the API Gateway for dynamic content.
  |
}


# API Gateway
grafbase: {
	shape: hexagon
	tooltip: |md
		Grafbase is used as our API gateway and aggregator.

		It allows us to provide a single API for all disparate service APIs.
	|
}

learner -> website
website -> grafbase: API Gateway

auth-service: {
	api: {
		tooltip: |md
			Register, Login, Token Exchange
		|
	}

	api -> turso
}

auth-service <-> grafbase

profile-service: {
	api: {
		tooltip: |md
			Fetch and Update Profiles
		|
	}

	api -> turso
}

profile-service <-> grafbase

rsvp-service: {
	api: {
		tooltip: |md
			Events RSVPs
		|
	}

	api -> turso
}

rsvp-service <--> grafbase

notification-service: {
	api: {
		tooltip: |md
			Send Notifications
		|
	}

	api -> turso
}

notification-service <-> grafbase

event-service: {
	api: {
		tooltip: |md
			Allow people to browse upcoming, scheduled, events
		|
	}

	api -> turso
}

event-service <-> grafbase

video-service: {
	api: {
		tooltip: |md
			Video hosting, streaming, and transcoding
		|
	}

	api -> turso
	api -> Cloudflare R2
}

video-service <-> grafbase

course-service: {
	api: {
		tooltip: |md
			Browse courses, lessons, and quizzes
		|
	}

	api -> turso
}

course-service <-> grafbase
