@default:
  just --list

# Get and Generate the Providers
build-providers:
  pnpm exec cdktf provider get

# Run the Rome Linter & Formatter
check:
  pnpm exec rome ci .

## CDKTF Commands
# Run cdktf Plan
plan stack="":
  op run -- pnpm exec cdktf plan {{ stack }}


# Run cdktf Deploy
deploy stack="":
  op run -- pnpm exec cdktf deploy {{ stack }}

# Bootstrap Kubernetes Cluster with FluxCD
bootstrap:
  kustomize build ./bootstrap | op inject | kubectl apply -f -

# Onboard all the teams
onboard:
  kubectl apply -k ./onboard/rawkode.community
  kubectl apply -k ./onboard/rawkode.studio
