image: nixos/nix:2.21.4

cache:
  paths:
    - /nix

default:
  before_script:
    - echo experimental-features = nix-command flakes >> /etc/nix/nix.conf
    - cd ./projects/rawkode-academy/web

web-bun-install:
  stage: setup
  script:
    - nix develop --impure . --command "bun" -- install

web-astro-check:
  stage: lint
  script:
    - nix develop --impure . --command "bun" -- x astro check

web-astro-build:
  stage: build
  script:
    - nix develop --impure . --command "bun" -- run build
  artifacts:
    paths:
      - ./projects/rawkode-academy/web/dist

web-deploy:
  stage: deploy
  dependencies:
    - web-astro-build
  environment:
    name: production
    url: https://rawkode.academy
  script:
    - nix develop --impure . --command "bun" -- x wrangler pages deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
