$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  sources:
    - '**/*.ts'
    - '**/*.js'
    - '**/*.json'

tasks:
  format:
    command: 'bun run biome format .'
    inputs:
      - '@group(sources)'
    options:
      runInCI: true
  lint:
    command: 'bun run biome lint .'
    inputs:
      - '@group(sources)'
    options:
      runInCI: true
