$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  deploy-read-model:
    deps:
      - lint
      - format
      - install
      - migrations-push
    env:
      LIBSQL_BASE_URL: rawkodeacademy.turso.io
    script: |
      bunx wrangler -c ./read-model/wrangler.jsonc deploy --var SERVICE_NAME:${SERVICE_NAME} --var LIBSQL_BASE_URL:${LIBSQL_BASE_URL}

      deno run -A read-model/publish.ts

      bunx wgc subgraph publish ${SERVICE_NAME} --namespace production --schema ./read-model/schema.gql --routing-url https://${SERVICE_NAME}-read-model.rawkodeacademy.workers.dev
      bunx wgc subgraph update ${SERVICE_NAME} --namespace production --routing-url https://${SERVICE_NAME}-read-model.rawkodeacademy.workers.dev
    options:
      runInCI: true
