$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  deploy-write-model:
    deps:
      - lint
      - format
      - install
    env:
      LIBSQL_BASE_URL: rawkodeacademy.turso.io
    script: |
      set -g OUTPUT $(op run -- bunx wrangler -c ./write-model/wrangler.jsonc deploy)
      set -g VERSION_ID $(echo "$OUTPUT" | grep -oP 'Current Version ID: \K[0-9a-f]{8}' | head -n 1)
      echo https://$VERSION_ID-$SERVICE_NAME-write-model.rawkodeacademy.workers.dev
      op run -- deno run -A --no-config 'npm:@restatedev/restate@1.1.2' deployments register --yes https://$VERSION_ID-$SERVICE_NAME-write-model.rawkodeacademy.workers.dev
    options:
      runInCI: true
