$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  deploy-write-model:
    deps:
      - lint
      - format
      - install
    env:
      LIBSQL_BASE_URL: rawkodeacademy.turso.io
    script: |
      op run -- bunx wrangler -c ./write-model/wrangler.jsonc deploy --var SERVICE_NAME:${SERVICE_NAME} --var LIBSQL_BASE_URL:${LIBSQL_BASE_URL}
    options:
      runInCI: true
