type Query {
  show(offset: Int, orderBy: ShowsTableOrderBy, where: ShowsTableFilters): ShowsTableSelectItem
  shows(offset: Int, limit: Int, orderBy: ShowsTableOrderBy, where: ShowsTableFilters): [ShowsTableSelectItem!]!
}

type ShowsTableSelectItem {
  id: String!
  name: String!
}

input ShowsTableOrderBy {
  id: InnerOrder
  name: InnerOrder
}

input InnerOrder {
  direction: OrderDirection!

  """Priority of current field"""
  priority: Int!
}

"""Order by direction"""
enum OrderDirection {
  """Ascending order"""
  asc

  """Descending order"""
  desc
}

input ShowsTableFilters {
  id: ShowsTableIdFilters
  name: ShowsTableNameFilters
  OR: [ShowsTableFiltersOr!]
}

input ShowsTableIdFilters {
  eq: String
  ne: String
  lt: String
  lte: String
  gt: String
  gte: String
  like: String
  notLike: String
  ilike: String
  notIlike: String

  """Array<undefined>"""
  inArray: [String!]

  """Array<undefined>"""
  notInArray: [String!]
  isNull: Boolean
  isNotNull: Boolean
  OR: [ShowsTableIdfiltersOr!]
}

input ShowsTableIdfiltersOr {
  eq: String
  ne: String
  lt: String
  lte: String
  gt: String
  gte: String
  like: String
  notLike: String
  ilike: String
  notIlike: String

  """Array<undefined>"""
  inArray: [String!]

  """Array<undefined>"""
  notInArray: [String!]
  isNull: Boolean
  isNotNull: Boolean
}

input ShowsTableNameFilters {
  eq: String
  ne: String
  lt: String
  lte: String
  gt: String
  gte: String
  like: String
  notLike: String
  ilike: String
  notIlike: String

  """Array<undefined>"""
  inArray: [String!]

  """Array<undefined>"""
  notInArray: [String!]
  isNull: Boolean
  isNotNull: Boolean
  OR: [ShowsTableNamefiltersOr!]
}

input ShowsTableNamefiltersOr {
  eq: String
  ne: String
  lt: String
  lte: String
  gt: String
  gte: String
  like: String
  notLike: String
  ilike: String
  notIlike: String

  """Array<undefined>"""
  inArray: [String!]

  """Array<undefined>"""
  notInArray: [String!]
  isNull: Boolean
  isNotNull: Boolean
}

input ShowsTableFiltersOr {
  id: ShowsTableIdFilters
  name: ShowsTableNameFilters
}
