@default:
  just --choose

# Clean up node_modules and generated providers
clean:
  rm -rf node_modules .gen

# Get and Generate the Providers
build-providers:
  bun x cdktf provider get

## CDKTF Commands
# Run cdktf Plan
plan stack="":
  op run -- bun x cdktf plan {{ stack }}


# Run cdktf Deploy
deploy stack="":
  op run -- bun x cdktf deploy {{ stack }}

deletelock:
  curl -XDELETE -d '{"ID": ""}' -u 'rawkodeacademy:PASSWORD' https://terraform-state-backend.rawkodeacademy.workers.dev/states/core-infrastructure-dns/lock
