default:
	just -l

db-clean:
	rm drizzle/local.db

db-gen:
	cd drizzle && bunx drizzle-kit generate:sqlite

db-migrate:
	cd drizzle && bun migrate.ts

db-seed:
	cd drizzle && bun seed.ts

db-studio:
	cd drizzle && bunx drizzle-kit studio
