# Forgejo OIDC Configuration for Zitadel
# This file should be mounted into the container at /etc/forgejo/app.ini.d/oidc.ini
# or manually added to the Forgejo configuration after initial setup

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[oauth2_client]
ENABLE_AUTO_REGISTRATION = true
ACCOUNT_LINKING = auto

[[oauth.oauth2]]
NAME = Zitadel
PROVIDER = openidConnect
KEY = 303319482200293448
SECRET = # This will need to be added via UI or secrets
AUTO_DISCOVER_URL = https://zitadel.rawkode.academy/.well-known/openid-configuration
SCOPES = openid profile email
REQUIRED_CLAIM_NAME = 
REQUIRED_CLAIM_VALUE = 
GROUP_CLAIM_NAME = groups
ADMIN_GROUP = 
RESTRICTED_GROUP = 
GROUP_TEAM_MAP = 
GROUP_TEAM_MAP_REMOVAL = false
USE_PKCE = true