dev:
	op inject --force --in-file .dev.vars.tpl --out-file .dev.vars
	bun x wrangler dev

deploy:
	-mv .envrc.production .envrc
	direnv allow
	op run --no-masking -- printenv DATABASE_URL
	op run --no-masking -- printenv DATABASE_AUTH_TOKEN
	op run -- bun run drizzle/migrate.ts
	direnv revoke
	mv .envrc .envrc.production

	bun x wrangler deploy
