@default:
  just --choose

# Get and Generate the Providers
build-providers:
  cdktf provider get

# Run the Rome Linter & Formatter
check:
  pnpm exec rome ci .

## CDKTF Commands
# Run cdktf Plan
plan stack="":
  op run -- cdktf plan {{ stack }}


# Run cdktf Deploy
deploy stack="":
  op run -- cdktf deploy {{ stack }}

# Bootstrap Kubernetes Cluster with FluxCD
bootstrap:
  kustomize build ./bootstrap | op inject | kubectl apply -f -
