name = "rawkode-academy"
pages_build_output_dir = "dist"
compatibility_date = "2023-01-23"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
compatibility_date = "2024-07-01"

[env.production.vars]
INFLUX_HOST="https://eu-central-1-1.aws.cloud2.influxdata.com"
INFLUX_ORG="Rawkode Academy"
INFLUX_BUCKET="analytics"
ZITADEL_CLIENT_ID="288679506217135064"
ZITADEL_URL="https://zitadel.rawkode.academy"
