name = "rawkode-academy"
pages_build_output_dir = "dist"
compatibility_date = "2023-01-23"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
compatibility_date = "2024-07-01"

[env.production.vars]
ZITADEL_CLIENT_ID="288679506217135064"
ZITADEL_URL="https://zitadel.rawkode.academy"
