name: casting-credits

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/casting-credits.yaml"
      - "projects/rawkode.academy/platform/casting-credits/**"
  pull_request:
    paths:
      - ".github/workflows/casting-credits.yaml"
      - "projects/rawkode.academy/platform/casting-credits/**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dagger
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh

      - name: Run Tests
        working-directory: projects/rawkode.academy/platform/casting-credits
        run: |
          dagger -m . call test --directory=.

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dagger
        run: |
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "rawkode-academy-production"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Get secrets from GCP Secret Manager
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |
            CLOUDFLARE_WORKERS_TOKEN:projects/458678766461/secrets/cloudflare-workers-token
            COSMO_API_KEY:projects/458678766461/secrets/cosmo-api-key

      - name: Deploy and Register Subgraph
        working-directory: projects/rawkode.academy/platform/casting-credits
        env:
          CLOUDFLARE_WORKERS_TOKEN: ${{ steps.secrets.outputs.CLOUDFLARE_WORKERS_TOKEN }}
          COSMO_API_KEY: ${{ steps.secrets.outputs.COSMO_API_KEY }}
          SERVICE_NAME: platform-casting-credits
        run: |
          dagger <<'.'
          repo=$(git https://github.com/dagger/hello-dagger | head | tree)
          env=$(container | from node:23 | with-directory /app $repo | with-workdir /app)
          build=$($env | with-exec npm install | with-exec npm run build | directory ./dist)
          container | from nginx | with-directory /usr/share/nginx/html $build | terminal --cmd=/bin/bash
          .
          dagger <<.
            codebase=$(../../../../dagger/bun | install --directory .)
            
            ../../../../dagger/cloudflare | deploy \
              $codebase \
              ./read-model/wrangler.jsonc \
              env:CLOUDFLARE_WORKERS_TOKEN
              
            ../../../../dagger/cloudflare | applyMigrations \
              $codebase \
              ./read-model/wrangler.jsonc \
              env:CLOUDFLARE_WORKERS_TOKEN \
              platform-casting-credits

            ../../../../dagger/wundergraph | generateAndPublishSubgraph \
              ${SERVICE_NAME} \
              production \
              $codebase \
              ./read-model/publish.ts \
              https://${SERVICE_NAME}-read-model.rawkode-academy.workers.dev \
              env:COSMO_API_KEY
          .
