name: Lint CODEOWNERS

on:
  pull_request:

jobs:
  codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check codeowners
        uses: gagoar/codeowners-generator@master
        with:
          use-maintainers: false
          check: true
