name: rawkode.academy/platform/video-guests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/platform-video-guests.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/video-guests/**"
  pull_request:
    paths:
      - ".github/workflows/platform-video-guests.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/video-guests/**"

jobs:
  deploy:
    uses: ./.github/workflows/platform-service-deploy.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      service-name: video-guests
      service-path: projects/rawkode.academy/platform/video-guests
      has-write-model: false
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
