name: rawkode.academy/platform/casting-credits

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/platform-casting-credits.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/casting-credits/**"
  pull_request:
    paths:
      - ".github/workflows/platform-casting-credits.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/casting-credits/**"

jobs:
  deploy:
    uses: ./.github/workflows/platform-service-deploy.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      service-name: casting-credits
      service-path: projects/rawkode.academy/platform/casting-credits
      has-write-model: true
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
