name: rawkode.academy/platform/videos

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/platform-videos.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/videos/**"
  pull_request:
    paths:
      - ".github/workflows/platform-videos.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/platform/videos/**"

jobs:
  deploy:
    uses: ./.github/workflows/platform-service-deploy.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      service-name: videos
      service-path: projects/rawkode.academy/platform/videos
      has-write-model: false
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
