name: rawkode.academy/website/preview

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/rawkode-academy-website.yaml"
      - "projects/rawkode.academy/web/**"

permissions:
   pull-requests: write

jobs:
  deploy:
    if: |
      github.event.review.state == 'approved' ||
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - shell: bash
        working-directory: "projects/rawkode.academy/web"
        run: source .env
      - id: deploy
        name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: bun
          command: pages deploy --project-name=rawkode-academy ./dist
          workingDirectory: "projects/rawkode.academy/web"
          preCommands: |
            bun run build
      - name: comment-with-preview-url
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            🌐 Your preview deployment can be viewed now 🚀

            ${{ steps.deploy.outputs.pages-deployment-alias-url }}
