name: rawkode.academy/website/preview

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/rawkode-academy-website-preview.yaml"
      - "projects/rawkode.academy/website/**"

permissions:
   pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest
      - shell: bash
        working-directory: "projects/rawkode.academy/website"
        run: source .env
      - id: deploy
        name: deploy
        # https://github.com/cloudflare/wrangler-action/issues/347
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: bun
          command: pages deploy --project-name=rawkode-academy ./dist
          workingDirectory: "projects/rawkode.academy/website"
          preCommands: |
            bun run build
      - name: comment-with-preview-url
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          message: |
            🌐 Your preview deployment can be viewed now 🚀

            ${{ steps.deploy.outputs.deployment-url }}
