name: rawkode.studio/deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rawkode-studio.yaml"
      - "projects/rawkode.studio/**"
  schedule:
    - cron: "12 4 * * *"

permissions:
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest
      - shell: bash
        working-directory: "projects/rawkode.studio"
        run: source .env
      - name: deploy
        # https://github.com/cloudflare/wrangler-action/issues/347
        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37 # v3.14.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: bun
          command: pages deploy --project-name=rawkode-studio ./dist
          workingDirectory: "projects/rawkode.studio"
          preCommands: |
            bun run build
